# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171219_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_informant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_sponsors',
            field=models.TextField(null=True),
        ),
    ]
