# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171220_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_youtube',
            field=models.TextField(null=True),
        ),
    ]
